name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Create env.properties file
      run : |
            cd src/main/resources
            touch env.properties
            echo "${{secrets.TEST_SECRETS}}" >> env.properties
    - name: Build with Maven
      run: mvn -B package --file pom.xml

